### PR TITLE
Remove `type` of options

### PR DESCRIPTION
**Pull request by AlexWayfer**
I don't know why it's here, it looks useless.

Make `:flag` an option (of option) with default `false`.

It's breaking changes, yes.

### CODE REVIEW

**Comment by mdub** [comment]
Is there a particular reason you suggested this change, @AlexWayfer?

The `type` field is used when generating help, to indicate the type of value that should be supplied to an option. IMHO pretty useful. 

As you mention, this is a breaking change, and removes functionality, so thanks but no thanks.

**Comment by AlexWayfer** [comment]
> The `type` field is used when generating help, to indicate the type of value that should be supplied to an option. IMHO pretty useful.

Can you please demonstrate a difference between `master` help generation and this branch?

**Comment by AlexWayfer** [comment]
> Is there a particular reason you suggested this change, @AlexWayfer?

See in the description: 

> I don't know why it's here, it looks useless.

I'm still waiting for your reply, for argumentation.

**Comment by AlexWayfer** [comment]
@mdub sorry, a friendly reminder.

**Comment by AlexWayfer** [comment]
Please.

**Comment by mdub** [comment]
Using one of the included examples, current behaviour is:

```
$ ./examples/admin --help
Usage:
    admin [OPTIONS] HOST [PORT]

Parameters:
    HOST                 server address
    [PORT]               server port (default: $MYAPP_PORT, or 80)

Options:
    --timeout SECONDS    connection timeout (default: $MYAPP_TIMEOUT, or 5)
    -h, --help           print help
```

With your changes, the output would be:

```
$ ./examples/admin --help
Usage:
    admin [OPTIONS] HOST [PORT]

Parameters:
    HOST          server address
    [PORT]        server port (default: $MYAPP_PORT, or 80)

Options:
    --timeout     connection timeout (default: $MYAPP_TIMEOUT, or 5)
    -h, --help    print help
```

It is useful to say `--timeout SECONDS` rather than simply `--timeout`, as it:
  1. let's the user know that the option expect an argument
  2. provides a hint as to what type of argument is expected

**Comment by AlexWayfer** [comment]
OK, I got it, thank you.

**Pull request closed without merging**
