### PR TITLE
Try command_class.subcommand_missing before signaling error

### PR DESCRIPTION
**Pull request by kke**
```ruby
Clamp do
  def subcommand_missing(name)
    if name == "foo"
      return Object.const_get(:FooPlugin) if Object.const_defined?(:FooPlugin)
      abort "Subcommand 'foo' requires plugin X"
    end
  end
end
```

### CODE REVIEW

**Comment by mdub** [comment]
Not a bad idea.

`Clamp::Command` could provide a default implementation, i.e.

```ruby
def subcommand_missing(name)
  def signal_usage_error(Clamp.message(:no_such_subcommand, :name => name))
end
```

which could clean up the conditional logic in `find_subcommand_class`.

Needs a test.

**Comment by kke** [comment]
Added the missing test and moved the default subcommand missing logic

**Comment by mdub** [comment]
What is `subcommand_missing` expected to return?  Your change to the README suggests it should be a `Class` (a subclass of `Clamp::Command`), but the implementation expects a `Clamp::Subcommand::Definition`.

A `Class` probably makes more sense.  So, perhaps the implementation of `find_subcommand_class` should be:

```ruby
def find_subcommand_class(name)
  subcommand_def = self.class.find_subcommand(name)
  return subcommand_def.subcommand_class if subcommand_def
  subcommand_missing(name)
end
```

What do you think, @kke?

**Comment by kke** [comment]
Yes, that's what I was trying. Now it's changed.

**Pull request merged**
